import type { Metadata } from "next";
import { RevenueChart } from "@/components/revenue-chart";
import { AddressPill, Badge, PageIntro, Panel, StatCard } from "@/components/ui";
import { mockTokens } from "@/lib/mock-data";
import { ARC_TESTNET_CONTRACTS } from "@/lib/chains";
import { money } from "@/lib/utils";
export const metadata:Metadata={title:"Fee Dashboard"};
const events=mockTokens.slice(0,7).map((token,i)=>({time:`${i*6+2}m ago`,source:i%4===0?"Launch":i%3===0?"Sell":"Buy",amount:i%4===0?25:8.2+i*3.4,payer:token.creator}));
export default function FeesPage(){return <><PageIntro eyebrow="Protocol economics" title="Every fee, made visible" body="ArcForge records protocol revenue by source in a deployed fee vault. Figures below are simulated until the testnet deployment is indexed."/><div className="container-shell pb-20"><div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><StatCard label="Total revenue" value="$8,240" detail="Demo values"/><StatCard label="Launch fees" value="$2,375" detail="25 USDC / launch"/><StatCard label="Buy fees" value="$3,481" detail="1.00%"/><StatCard label="Sell fees" value="$2,384" detail="1.00%"/><StatCard label="Migration fees" value="$0" detail="Not enabled"/></div><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_380px]"><Panel className="p-5"><div className="mb-5"><p className="eyebrow">Cumulative revenue</p><h2 className="mt-2 text-lg font-semibold">Protocol fee growth</h2></div><RevenueChart/></Panel><Panel className="p-5"><p className="eyebrow">Fee model</p><dl className="mt-5 grid gap-4 text-sm">{[["Launch fee","25 USDC","On token creation"],["Buy fee","1.00%","Of USDC input"],["Sell fee","1.00%","Of gross USDC output"],["Migration fee","0.25%","Planned; not enabled"],["Creator verification","Disabled","MVP"]].map(([label,value,note])=><div key={label} className="border-b border-line pb-3 last:border-0"><div className="flex justify-between"><dt className="text-slate-400">{label}</dt><dd className="font-medium text-white">{value}</dd></div><p className="mt-1 text-[10px] text-slate-600">{note}</p></div>)}</dl><div className="mt-5 rounded-xl border border-line bg-black/20 p-3"><p className="text-[10px] uppercase tracking-wider text-slate-600">Fee vault</p><div className="mt-2 flex items-center justify-between"><AddressPill address={ARC_TESTNET_CONTRACTS.feeVault}/><Badge tone="good">Deployed</Badge></div></div></Panel></div><Panel className="mt-5 overflow-hidden"><div className="border-b border-line p-5"><p className="eyebrow">Recent fee events</p></div><table className="w-full text-left text-xs"><thead><tr className="border-b border-line font-mono text-[9px] uppercase tracking-wider text-slate-600"><th className="px-5 py-3">Time</th><th>Source</th><th>Amount</th><th>Payer</th><th>Status</th></tr></thead><tbody>{events.map((event)=><tr key={`${event.payer}-${event.time}`} className="border-b border-line/60 last:border-0"><td className="px-5 py-3 text-slate-500">{event.time}</td><td><Badge tone={event.source==="Launch"?"cyan":event.source==="Buy"?"good":"bad"}>{event.source}</Badge></td><td className="text-slate-300">{money(event.amount)}</td><td><AddressPill address={event.payer}/></td><td><Badge tone="neutral">Simulated</Badge></td></tr>)}</tbody></table></Panel></div></>}
