import Link from "next/link";
import { ArrowRight, CircleDollarSign, Factory, Fingerprint, LineChart, LockKeyhole, ScanSearch, ShieldCheck, Sparkles } from "lucide-react";
import { mockTokens } from "@/lib/mock-data";
import { money } from "@/lib/utils";
import { LinkButton, Progress, RiskBadge, SectionHeading, StatCard, TokenIcon } from "@/components/ui";
import { TokenChart } from "@/components/token-chart";
import { HomeMarket } from "@/components/home-market";

export default function Home() {
  const featured = mockTokens[1];
  return <>
    <section className="grid-line relative overflow-hidden border-b border-line"><div className="container-shell grid min-h-[660px] items-center gap-12 py-20 lg:grid-cols-[1.05fr_.95fr]"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-cyan/20 bg-cyan/[.06] px-3 py-1.5 text-xs text-cyan"><Sparkles className="size-3"/>Built for early Arc mainnet liquidity</div><h1 className="max-w-4xl text-5xl font-semibold leading-[1.02] tracking-[-.055em] text-white md:text-7xl">Launch and discover<br/><span className="bg-gradient-to-r from-cyan via-[#a6eaff] to-violet bg-clip-text text-transparent">tokens on Arc</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-400">USDC bonding curves, transparent fees, creator reputation, real-time charts, and risk labels for the first wave of Arc-native tokens.</p><div className="mt-9 flex flex-wrap gap-3"><LinkButton href="/launch">Launch token <ArrowRight className="size-4"/></LinkButton><LinkButton href="/tokens" variant="secondary">Explore tokens</LinkButton></div><div className="mt-10 flex flex-wrap gap-x-8 gap-y-3 font-mono text-[10px] uppercase tracking-[.14em] text-slate-600"><span className="flex items-center gap-2"><LockKeyhole className="size-3 text-cyan"/>Fixed supply template</span><span className="flex items-center gap-2"><CircleDollarSign className="size-3 text-cyan"/>USDC native</span><span className="flex items-center gap-2"><ScanSearch className="size-3 text-cyan"/>Arcscan trail</span></div></div><div className="panel relative overflow-hidden p-4"><div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-cyan to-transparent"/><div className="flex items-center justify-between p-2"><div className="flex items-center gap-3"><TokenIcon label={featured.icon}/><div><div className="flex items-center gap-2"><p className="font-semibold text-white">{featured.name}</p><span className="font-mono text-[10px] text-slate-500">{featured.ticker}</span></div><p className="mt-1 text-xs text-slate-500">Live on Arc Testnet · demo feed</p></div></div><RiskBadge score={featured.riskScore}/></div><TokenChart data={featured.chartData} compact/><div className="grid grid-cols-3 gap-2 border-t border-line pt-3"><MiniStat label="Price" value={money(featured.price)}/><MiniStat label="24h volume" value={money(featured.volume24h, true)}/><MiniStat label="Curve" value={`${featured.curveProgress}%`}/></div><div className="mt-3"><Progress value={featured.curveProgress}/></div></div></div></section>
    <section className="container-shell py-20"><SectionHeading eyebrow="Arc Testnet market" title="One terminal for launch discovery" body="Factory launches use confirmed onchain data. Additional listings remain clearly labeled Demo." action={<Link href="/tokens" className="flex items-center gap-2 text-sm text-cyan">Open screener <ArrowRight className="size-4"/></Link>}/><div className="mt-8"><HomeMarket/></div></section>
    <section className="border-y border-line bg-white/[.012]"><div className="container-shell py-20"><SectionHeading eyebrow="Protocol flow" title="From idea to visible liquidity" body="A compact launch path with onchain rules that stay inspectable after deployment."/><div className="mt-10 grid gap-px overflow-hidden rounded-2xl border border-line bg-line md:grid-cols-4">{[
      { number: "01", title: "Configure", icon: Fingerprint, body: "Set identity, socials, allocation, and metadata." },
      { number: "02", title: "Launch", icon: Factory, body: "Factory deploys fixed supply and seeds the curve." },
      { number: "03", title: "Trade", icon: LineChart, body: "Buy and sell against a transparent USDC curve." },
      { number: "04", title: "Evaluate", icon: ShieldCheck, body: "Inspect risk labels, creator history, and holders." },
    ].map(({ number, title, icon: Icon, body }) => <div key={number} className="bg-panel p-6"><span className="font-mono text-xs text-cyan">{number}</span><Icon className="mt-8 size-6 text-slate-200"/><h3 className="mt-5 font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{body}</p></div>)}</div></div></section>
    <section className="container-shell py-20"><div className="grid gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="Risk intelligence" title="Context before speculation" body="Scores aggregate visible contract properties, creator history, social completeness, and concentration signals. They never guarantee safety."/><div className="mt-8 grid gap-3 sm:grid-cols-2">{[["Fixed supply","No post-launch mint path"],["Known template","Inspectable source assumptions"],["Holder signals","Concentration made visible"],["Creator reputation","History attached to the wallet"]].map(([title,body]) => <div key={title} className="panel p-4"><ShieldCheck className="size-5 text-cyan"/><p className="mt-4 text-sm font-medium text-white">{title}</p><p className="mt-1 text-xs text-slate-500">{body}</p></div>)}</div></div><div><SectionHeading eyebrow="Fee transparency" title="Revenue without hidden taxes" body="The MVP fee schedule is explicit in every quote and tracked by source in the fee vault."/><div className="mt-8 grid grid-cols-2 gap-3"><StatCard label="Launch fee" value="25 USDC" detail="Paid once at creation"/><StatCard label="Buy fee" value="1.00%" detail="Shown before approval"/><StatCard label="Sell fee" value="1.00%" detail="Deducted from output"/><StatCard label="Migration fee" value="Not enabled" detail="No migration fee is collected"/></div></div></div></section>
    <section className="container-shell pb-20"><div className="panel overflow-hidden bg-gradient-to-br from-cyan/[.07] via-panel to-violet/[.07] p-8 md:p-12"><div className="grid items-center gap-8 md:grid-cols-[1fr_auto]"><div><p className="eyebrow">Arc mainnet roadmap</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-white">Test the rails before mainnet liquidity arrives.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">ArcOrigin is configured for Arc Testnet today. Mainnet addresses remain unset until official chain values and USDC deployment details are provided.</p></div><LinkButton href="/docs">Read architecture <ArrowRight className="size-4"/></LinkButton></div></div></section>
    <footer className="border-t border-line"><div className="container-shell flex flex-col justify-between gap-5 py-8 text-xs text-slate-600 md:flex-row"><p>© 2026 ArcOrigin. Independent infrastructure for Arc. Not affiliated with or endorsed by Arc.</p><p>Not financial advice. Token launches are risky.</p></div></footer>
  </>;
}

function MiniStat({ label, value }: { label: string; value: string }) { return <div className="p-2"><p className="font-mono text-[9px] uppercase tracking-wider text-slate-600">{label}</p><p className="mt-1 text-xs font-medium text-slate-200">{value}</p></div>; }
