import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, Flame } from "lucide-react";
import { PageIntro, Progress, RiskBadge, TokenIcon } from "@/components/ui";
import { mockTokens } from "@/lib/mock-data";
import { calculateMomentumScore } from "@/lib/scoring";
import { money } from "@/lib/utils";
export const metadata: Metadata = { title: "Trending Launches" };
export default function TrendingPage() { const ranked = mockTokens.map((token)=>({ token, score: calculateMomentumScore(token) })).sort((a,b)=>b.score-a.score); return <><PageIntro eyebrow="Momentum index" title="What is moving on Arc" body="Momentum combines volume velocity, buyers, trades, curve progress, age decay, and a risk penalty. It measures activity—not quality or expected returns."/><div className="container-shell pb-20"><div className="panel overflow-hidden">{ranked.map(({token,score},i)=><Link href={`/tokens/${token.address}`} key={token.address} className="grid items-center gap-4 border-b border-line/70 p-4 transition last:border-0 hover:bg-white/[.025] md:grid-cols-[56px_1.3fr_1fr_1fr_1fr_auto]"><div className="flex items-center gap-2"><span className="font-mono text-lg text-slate-600">{String(i+1).padStart(2,"0")}</span>{i<3&&<Flame className="size-4 text-amber-300"/>}</div><div className="flex items-center gap-3"><TokenIcon label={token.icon}/><div><p className="font-semibold text-white">{token.name}</p><p className="text-[10px] text-slate-500">{token.ticker}</p></div></div><div><p className="font-mono text-[9px] uppercase tracking-wider text-slate-600">Momentum</p><p className="mt-1 text-xl font-semibold text-white">{score}<span className="text-xs text-slate-600">/100</span></p></div><div><p className="font-mono text-[9px] uppercase tracking-wider text-slate-600">24h volume</p><p className="mt-1 text-sm text-slate-200">{money(token.volume24h,true)}</p></div><div><div className="mb-2 flex justify-between text-[10px] text-slate-500"><span>Curve</span><span>{token.curveProgress}%</span></div><Progress value={token.curveProgress}/></div><div className="flex items-center gap-3"><RiskBadge score={token.riskScore}/><ArrowUpRight className="size-4 text-slate-600"/></div></Link>)}</div></div></>; }
